name: Create Documentation Issue

on:
  pull_request:
    types: [labeled]

jobs:
  check-label-and-create-issue:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'needs documentation'
    steps:
      - name: Create Docs Issue
        uses: actions/github-script@v7
        with:
          script: |
            const githubToken = '${{ secrets.GH_TOKEN }}';
            const octokit = github.getOctokit(githubToken);

            const title = `Document: ${context.payload.pull_request.title}`;
            const body = `We need to document the new feature introduced in this PR: ${context.payload.pull_request.html_url}`;

            await octokit.rest.issues.create({
              owner: 'evcc-io',
              repo: 'docs',
              title: title,
              body: body
            });
